export const DepotInitialValue = {
    phoneNumber: "",
    email: [],
    companyEmail: "",
    companyName: "",
    logo: "",
    address: "",
    // subscription_plan: "",
    regionLimit: "",
    // trial_period: "",
    jobQualificationId: "",
    jobRateDepotFirstDisplayedToDepot: "",
    jobRateDepotFirstDisplayedToOp: "",
    jobRateMeetOnsiteDisplayedToDepot: "",
    jobRateMeetOnsiteDisplayedToOp: "",
}
