export const DepotInitialValue = {
    phoneNumber: "",
    email: [],
    companyEmail: "",
    companyName: "",
    logo: "",
    address: "",
    // subscription_plan: "",
    num_of_locations: "",
    // trial_period: "",
    qualification_category: "",
    findersforce_depot_amount: "",
    findersforce_meet_amount: "",
    operative_depot_amount: "",
    operative_meet_amount: "",
}
